import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "~/components/Navbar";
import clsx from "clsx";
import Footer from "~/components/Footer";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={clsx(dmSans.className, "bg-[#040504] text-white")}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
